### PR TITLE
Fix Merge Conficts

### PR DESCRIPTION
**Pull request by wormeyman**
Sorry about that!

### CODE REVIEW

**Comment by akash-vartak** [comment]
Done sir!

**Comment by akash-vartak** [comment]
Ready now??

**Comment by wormeyman** [comment]
Yeah go for it @akash-vartak

**Comment by akash-vartak** [comment]
So now I shall download a zip of my repo and upload the same at the link you gave me , right?

**Comment by wormeyman** [comment]
Yes you can just use the zip button on github or `git archive --format zip -o yourextension.zip master` like it says here https://github.com/adobe/brackets/wiki/Extension-Registry-Help

**Comment by akash-vartak** [comment]
Thanks, and I had silly doubt, about how I would be credited for the theme??
Also a question about Brackets organisation?

**Comment by wormeyman** [comment]
The credit for the theme is in you `package.json` that is where it pulls the info for the registry.

**Comment by akash-vartak** [comment]
ohk ohk, Thanks!! 
Also I noticed that the theme is immediately listed under Themes instead of Available tab in Extension Manager.

**Comment by wormeyman** [comment]
Right, themes are their own category.

**Comment by akash-vartak** [comment]
Ohk right, obviously!! 

<h3>Thanks for all the help!!</h3>

**Comment by akash-vartak** [comment]
:metal:

**Pull request merged**
