### PR TITLE
Some small changes before you submit

### PR DESCRIPTION
**Pull request by wormeyman**
1. You do not need a main.js
2. Consistency with your tabs and spaces (not a big deal)

### CODE REVIEW

**Comment by akash-vartak** [comment]
what are these changes??

**Comment by wormeyman** [comment]
They are listed above:

> 1. You do not need a main.js
> 2. Consistency with your tabs and spaces (not a big deal)

**Comment by akash-vartak** [comment]
right right

**Comment by akash-vartak** [comment]
hey i am having a small problem. I am not able to merge. The button is inactive. It says "This branch has conflicts that must be resolved"

**Comment by akash-vartak** [comment]
Merged!! Is the theme ready now??

**Comment by wormeyman** [comment]
I sent another pull request for the merge conflict @akash-vartak then it should be ready :grin:

**Pull request merged**
